[tool.poetry]
name = "sec-parser"
version = "0.2.0"
description = "A robust and efficient parser for SEC filings, designed to extract and analyze financial data with ease."
authors = ["Alphanome.AI <info@alphanome.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
flake8-black = "^0.3.6"
isort = "^5.12.0"
mypy = "^1.5.1"
coverage = "^7.3.1"
commitizen = "^3.8.1"
pre-commit = "^3.4.0"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
