version: '3'

tasks:

######################################################
### Development Tools: Local Application Launchers ###
######################################################

  launch-debug-dashboard:
    desc: Start a local debugging dashboard in the browser.
    cmds:
      # Using PYTHONPATH to allow Streamlit to monitor file changes. Learn more: https://docs.streamlit.io/knowledge-base/using-streamlit/streamlit-watch-changes-other-modules-importing-app
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/sec_parser ENVIRONMENT=dev && poetry run streamlit run dev_utils/debug_dashboard/app.py --server.runOnSave=true

  monitor-unit-tests:
    desc: "Run unit tests and rerun them immediately upon file modification."
    cmds:
      # Recommended coverage viewer in VSCode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
      # Note: also update .codecov.yml when changing the target coverage.
      - poetry run ptw -- -- -s --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered --cov-fail-under=90 {{.CLI_ARGS}} tests/unit/

  launch-docs:
    desc: Start a local server to preview and automatically rebuild documentation upon file modification.
    cmds:
      - poetry run sphinx-autobuild docs/source docs/build/html
      
########################################
### Automated Code Testing Pipelines ###
########################################

  pre-commit-checks: 
    desc: Execute all pre-commit checks before committing code.
    cmds:
      - task: unit-tests
      - task: lint

  pre-push-checks:
    desc: Execute all pre-push checks before pushing code or creating a PR.
    cmds:
      - task: ensure-clean-working-tree
      - task: ci-checks
      - task: ensure-clean-working-tree

  ci-checks:
    desc: Execute all CI/CD checks for debugging a failing CI/CD pipeline.
    cmds:
      - task: unit-tests
      - task: lint-without-autofix
      - task: verify-docs-integrity
      - task: e2e-verify-dataset

####################################
### Additional Development Tools ###
####################################

  e2e-verify-dataset:
    desc: Validate the end-to-end dataset snapshots against the latest parser outputs.
    silent: true
    cmds:
      - task: clone-sec-parser-validation-data
      # Checking if the sec-parser-validation-data directory has any changes in the working tree or index. If it does, aborting.
      - cd "{{.ROOT_DIR}}/../sec-parser-validation-data" && if git diff --exit-code > /dev/null 2>&1 && git diff --cached --exit-code > /dev/null 2>&1; then :; else echo "Changes detected in the working tree or index of the sec-parser-validation-data repository. Please commit or stash them before proceeding."; exit 1; fi
      - poetry run python -m tests.e2e verify {{.CLI_ARGS}}

  e2e-generate-dataset:
    desc: Create end-to-end dataset snapshots using the latest parser outputs.
    silent: true
    cmds:
      - task: clone-sec-parser-validation-data
      - task: ensure-clean-working-tree
      - poetry run python -m tests.e2e generate {{.CLI_ARGS}}
      - "echo -e \"Please review the generated snapshot in sec-parser-validation-data.\nIf correct, commit it to the repository.\nInclude the sec-parser hash in the commit message: $(git rev-parse HEAD)\""

################################################################
### Hidden: Primarily Used within Other Tasks or Used Rarely ###
################################################################

  unit-tests: # Execute unit tests and assess code coverage.
    cmds:
      # Recommended coverage viewer in VSCode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
      # Note: also update .codecov.yml when changing the target coverage.
      - poetry run pytest -s --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered --cov-fail-under=90 {{.CLI_ARGS}} tests/unit/

  lint: # Perform linting on the code and automatically fix issues.
    cmds:
      - poetry run ruff check --fix sec_parser/
      - poetry run mypy

  lint-without-autofix: # Perform linting on the code without auto-fixing issues.
    cmds:
      - poetry run ruff check sec_parser/
      - poetry run mypy

  verify-docs-integrity: # Check the integrity of the documentation.
    silent: true
    cmds:
      - poetry export --with doc -f requirements.txt --output docs/rtd_requirements.txt
      - echo "[Taskfile] Executing notebooks and checking for errors. The output will be saved to the notebook files."
      - for file in $(find {{.ROOT_DIR}}/docs/source/notebooks -name "*.ipynb"); do echo -n "Processing file \"$file\"... "; poetry run exec_nb --exc_stop $file --dest $file && echo "done!" || { echo "Processing failed for file \"$file\""; exit 1; }; done

  ensure-clean-working-tree: # Ensure no changes in the working tree or index, abort if any.
    silent: true
    internal: true
    cmds:
      - if git diff --exit-code > /dev/null 2>&1 && git diff --cached --exit-code > /dev/null 2>&1; then :; else echo "Changes detected in the working tree or index. Please commit or stash them before proceeding."; exit 1; fi

  version-bump: # Increment the version number.
    cmds:
      - poetry run cz bump {{.CLI_ARGS}}
      - poetry export --with doc -f requirements.txt --output docs/rtd_requirements.txt

  clone-sec-parser-validation-data: # Clone the 'sec-parser-validation-data' repository if it's not already present.
    silent: true
    cmds:
      - if [ -d "{{.ROOT_DIR}}/../sec-parser-validation-data" ]; then :; else echo "Repository does not exist. Cloning from GitHub..."; git clone https://github.com/alphanome-ai/sec-parser-validation-data "{{.ROOT_DIR}}/../sec-parser-validation-data" || { echo "Directory ../sec-parser-validation-data does not exist and git clone failed. Please use \"git clone\" to download it from https://github.com/alphanome-ai/sec-parser-validation-data. Aborting."; exit 1; }; fi

  check-and-push:
    cmds:
      - task: pre-push-checks
      - git push

######################################
### Shorthand Tasks for Efficiency ###
######################################

  c: # You can just run `task c` instead of `task pre-commit-checks`.
    deps:
      - pre-commit-checks

  p: # You can just run `task p` instead of `task pre-push-checks`.
    deps:
      - pre-push-checks

  pp: # You can just run `task pp` instead of `task check-and-push`.
    deps:
      - check-and-push

  d: # You can just run `task d` instead of `task launch-debug-dashboard`.
    deps:
      - launch-debug-dashboard

  m: # You can just run `task m` instead of `task monitor-unit-tests`.
    deps:
      - monitor-unit-tests

  x: # You can just run `task x` instead of `task launch-docs`.
    deps:
      - launch-docs

  xx: # You can just run `task xx` instead of `task verify-docs-integrity`.
    deps:
      - verify-docs-integrity
