version: '3'

tasks:
  test:
    desc: Run tests and check code coverage
    cmds:
      # Recommended coverage viewer in VSCode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
      - pytest --cov --cov-report=lcov:lcov.info tests/
      - coverage report --skip-covered --fail-under=0

  lint:
    desc: Lint the code
    cmds:
      - ruff check --fix sec_parser/
      - mypy sec_parser/

  prepare: 
    desc: Lint the code and run all checks
    deps: [test, lint]

  visualize-output:
    desc: Run the parser output visualizer
    cmds:
      - streamlit run debug_tools/parser_output_visualizer/app.py --server.runOnSave=true