version: '3'

tasks:
  unit:
    desc: Run unit tests and check code coverage
    cmds:
      # Recommended coverage viewer in VSCode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
      - pytest -s --cov --cov-report=lcov:lcov.info tests/unit/
      - coverage report --skip-covered --fail-under=0

  lint:
    desc: Lint the code
    cmds:
      - ruff check --fix sec_parser/
      # mirrors mypy.ini config of keeping all checked files in a single folder
      - mypy sec_parser/

  prepare: 
    desc: Lint the code and run all checks
    cmds:
      - task unit && task lint # Doing like this instead of `deps` to determine order of execution

  visual:
    desc: Run the parser output visualizer
    cmds:
      # PYTHONPATH is added to make streamlit watch file changes. Read more: https://docs.streamlit.io/knowledge-base/using-streamlit/streamlit-watch-changes-other-modules-importing-app
      - PYTHONPATH=$PYTHONPATH:$(pwd)/sec_parser streamlit run debug_tools/parser_output_visualizer/app.py --server.runOnSave=true

  speed:
    desc: Run speed tests
    cmds:
      - python -m tests.e2e.speed.parse
